/*Template generated by WebStorm on Sunday (5/7/23), 8:26 PM.
 * Author: kramstyles
 * Filename: CocktailList.jsx
 */

import { useCocktailContext } from "./context";
import Loader from "../../components/Loader";

const CocktailList = () => {
  const { loading, cocktails } = useCocktailContext();
  if (loading) {
    return <Loader />;
  }
  if (cocktails.length < 1)
    return (
      <h2 className="text-center">
        No cocktail matched your search criteria.
      </h2>
    );
  return (
    <div className="container">
      <h1>CocktailList</h1>
    </div>
  );
};

export default CocktailList;
