/*Template generated by WebStorm on Sunday (5/7/23), 8:26 PM.
* Author: kramstyles
* Filename: CocktailList.jsx
*/

const CocktailList = () => {
    return (
        <div className="container">
            <h1>CocktailList</h1>
        </div>
    );
};

export default CocktailList;
