/*Template generated by WebStorm on Sunday (5/7/23), 8:26 PM.
 * Author: kramstyles
 * Filename: CocktailList.jsx
 */

import { useCocktailContext } from "./context";
import Single from "./Single";
import Loader from "../../components/Loader";

const CocktailList = () => {
  const { loading, cocktails } = useCocktailContext();
  if (loading) {
    return <Loader />;
  }
  if (cocktails.length < 1)
    return (
      <h2 className="text-center">No cocktail matched your search criteria.</h2>
    );
  else
    return (
      <div className="row justify-content-center">
        <div className="my-3"></div>
        {cocktails.map((item) => {
          return (
            <div className="col-md-4 my-2" key={item.id}>
              <Single {...item} />
            </div>
          );
        })}
      </div>
    );
};

export default CocktailList;
