/*Template generated by WebStorm on Sunday (5/7/23), 8:25 PM.
 * Author: kramstyles
 * Filename: Cocktail.jsx
 */

import SearchForm from "./SearchForm";
import CocktailList from "./CocktailList";

const Cocktail = () => {
  return (
    <div className="container">
      <SearchForm />
      <CocktailList />
    </div>
  );
};

export default Cocktail;
