/*Template generated by WebStorm on Sunday (5/7/23), 8:25 PM.
* Author: kramstyles
* Filename: SearchForm.jsx
*/

const SearchForm = () => {
    return (
        <div className="container">
            <h1>SearchForm</h1>
        </div>
    );
};

export default SearchForm;
