/*Template generated by WebStorm on Monday (5/8/23), 2:11 PM.
 * Author: kramstyles
 * Filename: Single.jsx
 */

import PropTypes from "prop-types";
import { Link } from "react-router-dom";

const Single = ({ id, name, info, image, glass }) => {
  return (
    <div className="card">
      <img className="card-img-top w-100" src={image} alt={name} />
      <div className="card-body">
        <h4 className="card-title">{name}</h4>
        <p className="card-text m-0">{glass}</p>
        <p className="card-text text-muted m-0">{info}</p>
      </div>
      <div className="card-footer">
        <Link
          to={`projects/cocktails/${id}`}
          className="btn btn-primary btn-sm m-1"
        >
          More Information
        </Link>
      </div>
    </div>
  );
};

Single.propTypes = {
  id: PropTypes.string.isRequired,
  name: PropTypes.string.isRequired,
  image: PropTypes.string.isRequired,
  info: PropTypes.string.isRequired,
  glass: PropTypes.string.isRequired,
};

export default Single;
