/*Template generated by WebStorm on Thursday (5/11/23), 12:28 PM.
* Author: kramstyles
* Filename: Bar3D.jsx
*/

const Bar3D = () => {
    return (
        <div className="container">
            <h1>Bar3D</h1>
        </div>
    );
};

export default Bar3D;
