/*Template generated by WebStorm on Thursday (5/11/23), 12:28 PM.
* Author: kramstyles
* Filename: Column3D.jsx
*/

const Column3D = () => {
    return (
        <div className="container">
            <h1>Column3D</h1>
        </div>
    );
};

export default Column3D;
