/*Template generated by WebStorm on Thursday (5/11/23), 12:29 PM.
* Author: kramstyles
* Filename: Donut2D.jsx
*/

const Donut2D = () => {
    return (
        <div className="container">
            <h1>Donut3D</h1>
        </div>
    );
};

export default Donut2D;
