/*Template generated by WebStorm on Thursday (5/11/23), 12:29 PM.
 * Author: kramstyles
 * Filename: Pie3D.jsx
 */

import PropTypes from "prop-types";

import ReactFC from "react-fusioncharts";
import FusionCharts from "fusioncharts";
import Charts from "fusioncharts/fusioncharts.charts";
import FusionTheme from "fusioncharts/themes/fusioncharts.theme.gammel";

ReactFC.fcRoot(FusionCharts, Charts, FusionTheme);
const Pie3D = ({ data }) => {
  const chartConfigs = {
    type: "pie3d",
    width: "100%",
    height: "500",
    dataFormat: "json",
    dataSource: {
      chart: {
        caption: "Languages",
        subCaption: "Popular Programming Languages",
        theme: "gammel",
        pieRadius: "50%",
      },
      // Chart data
      data,
    },
  };
  return (
    <div className="col-md-6">
      <ReactFC {...chartConfigs} />
    </div>
  );
};

Pie3D.propTypes = {
  data: PropTypes.array.isRequired,
};

export default Pie3D;
