/*Template generated by WebStorm on Thursday (4/27/23), 12:01 PM.
* Author: kramstyles
* Filename: Navbar.jsx
*/

const Navbar = () => {
    return (
        <div className="container">
            <h1>Navbar</h1>
        </div>
    );
};

export default Navbar;
