/*Template generated by WebStorm on Thursday (4/27/23), 12:01 PM.
 * Author: kramstyles
 * Filename: Navbar.jsx
 */

import { useStripeContext } from "./context";
import { FaHamburger } from "react-icons/fa";

const Navbar = () => {
  const { toggleSidebar, openSubmenu, closeSubmenu, sublinks } =
    useStripeContext();
  const displaySubmenu = (e) => {
    const tempButton = e.target.getBoundingClientRect();
    const page = e.target.textContent;
    const center = (tempButton.left + tempButton.right) / 2;
    const bottom = tempButton.bottom;
    openSubmenu(page, { center, bottom });
  };
  const handleCloseSubmenu = (e) => {
    if (!e.target.classList.contains("my-nav-link")) closeSubmenu();
  };
  return (
    <div
      className="my-navbar d-flex justify-content-between p-3 align-items-center"
      onMouseOver={(e) => handleCloseSubmenu(e)}
    >
      <a
        href="https://mark-eke.netlify.app"
        className="fs-2 text-decoration-none text-light text-shadow fw-bold"
      >
        Stripe Menu
      </a>
      <section className="hide-on-small-devices">
        <div className="my-link-group justify-content-between">
          {sublinks.map((item, index) => {
            const { page } = item;
            return (
              <button
                className="btn p-5 text-capitalize fw-bold my-nav-link"
                key={index}
                onMouseOver={(e) => displaySubmenu(e)}
              >
                {page}
              </button>
            );
          })}
        </div>
      </section>
      <div className="hide-on-small-devices">
        <button className="btn btn-outline-dark">Sign In</button>
      </div>
      <div className="show-on-small-devices">
        <button className="btn btn-outline-dark" onClick={toggleSidebar}>
          <FaHamburger className="fs-3" />
        </button>
      </div>
    </div>
  );
};

export default Navbar;
