/*Template generated by WebStorm on Thursday (4/27/23), 12:02 PM.
 * Author: kramstyles
 * Filename: SideBar.jsx
 */

import { useStripeContext } from "./context";
import { FaTimesCircle } from "react-icons/fa";

const SideBar = () => {
  const { toggleSidebar, isSidebar, sublinks } = useStripeContext();
  return (
    <section className="show-on-small-devices">
      <div className={`sidebar-wrapper${isSidebar ? " show" : ""}`}>
        <div className="sidebar-dialog bg-white shadow">
          <div className="text-end p-3">
            <FaTimesCircle
              className="text-danger fs-2 cur-pointer"
              onClick={toggleSidebar}
            />
          </div>
          <div className="p-3">
            {sublinks.map((item, index) => {
              const { links, page } = item;
              return (
                <div className="my-3 text-capitalize" key={index}>
                  <h3 className="fw-bold">{page}</h3>
                  <div className="row justify-content-center">
                    {links.map((link, index) => {
                      const { label, icon, url } = link;
                      return (
                        <div className="col-6 my-1">
                          <a
                            href={`https:/${url}`}
                            className="text-dark text-decoration-none"
                          >
                            {icon} {label}
                          </a>
                        </div>
                      );
                    })}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      </div>
    </section>
  );
};

export default SideBar;
