/*Template generated by WebStorm on Thursday (4/27/23), 12:02 PM.
* Author: kramstyles
* Filename: SideBar.jsx
*/

const SideBar = () => {
    return (
        <div className="container">
            <h1>SideBar</h1>
        </div>
    );
};

export default SideBar;
