/*Template generated by WebStorm on Thursday (4/27/23), 12:01 PM.
* Author: kramstyles
* Filename: SubMenu.jsx
*/

import {useStripeContext} from "./context";
import {useEffect, useRef} from "react";
const SubMenu = () => {
    const {isSubmenu, location} = useStripeContext();
    const container = useRef(null);

    useEffect(()=> {
        const subMenu = container.current;
        const {center} = location;
        subMenu.style.left = `${center - (subMenu.offsetWidth / 2)}px`;
    }, [location])

    return (
        <div className="position-relative">
            <div className={`my-tooltip shadow${isSubmenu? " show": ""}`} ref={container}></div>
        </div>
    );
};

export default SubMenu;
