/*Template generated by WebStorm on Tuesday (5/9/23), 4:21 PM.
 * Author: kramstyles
 * Filename: AuthWrapper.jsx
 */

const AuthWrapper = () => {
  return (
    <div className="container">
      <h1>AuthWrapper</h1>
    </div>
  );
};

export default AuthWrapper;
