/*Template generated by WebStorm on Tuesday (5/9/23), 4:21 PM.
 * Author: kramstyles
 * Filename: AuthWrapper.jsx
 */

import { Auth0Provider } from "@auth0/auth0-react";
import { GithubProvider } from "../context/context";

// Domain & Client ID
const DOMAIN = process.env.REACT_APP_AUTH_DOMAIN;
const CLIENT_ID = process.env.REACT_APP_AUTH_CLIENT_ID;

const AuthWrapper = ({ children }) => {
  return (
    <Auth0Provider
      domain={DOMAIN}
      clientId={CLIENT_ID}
      redirectUri={window.location.origin}
      cacheLocation={"localstorage"} // to remain logged in as you visit other pages
    >
      <GithubProvider>{children}</GithubProvider>
    </Auth0Provider>
  );
};

export default AuthWrapper;
