/*Template generated by WebStorm on Tuesday (5/9/23), 4:21 PM.
 * Author: kramstyles
 * Filename: Dashboard.jsx
 */

import { Info, Repos, User, NavBar, Search } from "../components";

const Dashboard = () => {
  return (
    <>
        <NavBar />
        <div className="container">
            <Search />
            <Info />
            <User />
            <Repos />
        </div>
    </>
  );
};

export default Dashboard;
