/*Template generated by WebStorm on Tuesday (5/9/23), 4:21 PM.
* Author: kramstyles
* Filename: Dashboard.jsx
*/

const Dashboard = () => {
    return (
        <div className="container">
            <h1>Dashboard</h1>
        </div>
    );
};

export default Dashboard;
