/*Template generated by WebStorm on Tuesday (5/9/23), 4:23 PM.
 * Author: kramstyles
 * Filename: Login.jsx
 */
import Jumbotron from "../../components/Jumbotron";
import LoginImage from "../components/images/user-login2.png";
const Login = () => {
  return (
    <>
      <Jumbotron title="Github Login" />
      <div className="container">
        <div className="row">
          <div className="col-md-6 offset-md-3 text-center">
            <img src={LoginImage} alt="Github Login" className="w-75" />
            <div>
              <button className="btn btn-dark px-5 my-3">Login</button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
};

export default Login;
