/*Template generated by WebStorm on Tuesday (5/9/23), 4:23 PM.
* Author: kramstyles
* Filename: Login.jsx
*/
import Jumbotron from "../../components/Jumbotron";
const Login = () => {
    return (
        <>
            <Jumbotron title="Github Login"/>
            <div className="container">
                <h1>Login</h1>
            </div>
        </>
    );
};

export default Login;
