/*Template generated by WebStorm on Sunday (3/17/24), 7:57 PM.
* Author: kramstyles
* Filename: LoginWrapper.jsx
*/
import AuthWrapper from "./AuthWrapper";
import Login from "./Login";

const LoginWrapper = () => {
    return (
        <AuthWrapper>
            <Login />
        </AuthWrapper>
    );
};

export default LoginWrapper;
