/*Template generated by WebStorm on Tuesday (5/9/23), 4:24 PM.
 * Author: kramstyles
 * Filename: PrivateRoute.jsx
 */

import { Outlet, Navigate } from "react-router-dom";

const PrivateRoute = () => {
  let user = sessionStorage.getItem("isGitUser");
  if (!user) {
    user = false
  } else{
    user = JSON.parse(user);
  }
  return (
      user ? <Outlet /> : <Navigate to={"/github/login"} />
    // <Outlet{...rest}>
    //     {!isUser ? <Navigate to={"/github/login"}/> : children}
    // </Outlet>
  );
};

export default PrivateRoute;
