/*Template generated by WebStorm on Tuesday (5/9/23), 4:24 PM.
* Author: kramstyles
* Filename: PrivateRoute.jsx
*/

const PrivateRoute = () => {
    return (
        <div className="container">
            <h1>PrivateRoute</h1>
        </div>
    );
};

export default PrivateRoute;
