/*Template generated by WebStorm on Tuesday (5/9/23), 4:24 PM.
 * Author: kramstyles
 * Filename: PrivateRoute.jsx
 */

import { Route, Navigate } from "react-router-dom";

const PrivateRoute = ({ children, ...rest }) => {
  const isUser = true;
  return (
    <Route
      {...rest}
      render={() => {
        return isUser ? children : <Navigate to={"/github/login"}></Navigate>;
      }}
    ></Route>
  );
};

export default PrivateRoute;
