/*Template generated by WebStorm on Wednesday (4/26/23), 7:07 PM.
* Author: kramstyles
* Filename: context.jsx
*/

import {useState, useContext, createContext} from "react";

const AppContext = createContext();

const AppProvider = ({children}) => {
    return <AppContext.Provider value="hello">{children}</AppContext.Provider>
}

export {AppContext, AppProvider};
