/*Template generated by WebStorm on Wednesday (4/26/23), 5:29 PM.
* Author: kramstyles
* Filename: Home.jsx
*/

import {GiHamburgerMenu} from "react-icons/gi";

const Home = () => {
    return (
        <div className="fs-1 d-flex m-5" style={{height: "75vh"}}>
            <GiHamburgerMenu className="cur-pointer text-primary throb"/>
            <button className="btn btn-dark m-auto">SHOW MODAL</button>
        </div>
    );
};

export default Home;
