/*Template generated by WebStorm on Wednesday (4/26/23), 5:22 PM.
* Author: kramstyles
* Filename: Sidebar.jsx
*/

const Sidebar = () => {
    return (
        <div className="container">
            <h1>Sidebar</h1>
        </div>
    );
};

export default Sidebar;
