/*Template generated by WebStorm on Wednesday (4/26/23), 5:22 PM.
 * Author: kramstyles
 * Filename: Sidebar.jsx
 */

import { socialLinks } from "../11NavBar/data";
import { FaTimes } from "react-icons/fa";

const Sidebar = () => {
  return (
    <div className="position-absolute my-sidebar-container">
      <div className="my-sidebar border-primary border-end">
        <div className="text-end p-5">
          <FaTimes className="fs-1 text-danger cur-pointer" />
        </div>
          <div className="p-2 list-group">
              {socialLinks.map((link, index) => {
                  const { icon, url, name } = link;
                  return (
                      <a
                          href={url} key={index}
                          className="list-group-item list-group-item-action text-capitalize text-primary p-3"
                      >
                          {icon} {name}
                      </a>
                  );
              })}
          </div>
      </div>
    </div>
  );
};

export default Sidebar;
