/*Template generated by WebStorm on Sunday (5/7/23), 8:43 PM.
* Author: kramstyles
* Filename: CocktailDetail.jsx
*/

import Jumbotron from "../../../components/Jumbotron";
import {useParams} from "react-router-dom";

const CocktailDetail = () => {
    const {id} = useParams();
    return (
        <>
            <Jumbotron title={`Cocktail ${id}`} />
            <div className="container">
                <div className="row">

                </div>
            </div>
        </>
    );
};

export default CocktailDetail;
