/*Template generated by WebStorm on Sunday (5/7/23), 8:43 PM.
* Author: kramstyles
* Filename: CocktailDetail.jsx
*/

import Jumbotron from "../../../components/Jumbotron";

const CocktailDetail = () => {
    return (
        <>
            <Jumbotron title={"Single Cocktail"} />
            <div className="container">
                <div className="row">
                    <h1>Details about the cocktail in a card</h1>
                </div>
            </div>
        </>
    );
};

export default CocktailDetail;
