/*Template generated by WebStorm on Friday (4/28/23), 7:07 PM.
* Author: kramstyles
* Filename: CartItem.jsx
*/

const CartItem = () => {
    return (
        <div className="container">
            <h1>CartItem</h1>
        </div>
    );
};

export default CartItem;
