/*Template generated by WebStorm on Friday (4/28/23), 7:07 PM.
* Author: kramstyles
* Filename: CartContainer.jsx
*/

const CartContainer = () => {
    return (
        <div className="container">
            <h1>CartContainer</h1>
        </div>
    );
};

export default CartContainer;
