/*Template generated by WebStorm on Friday (4/28/23), 7:07 PM.
* Author: kramstyles
* Filename: Navbar.jsx
*/

import {useCartContext} from "./context";

const Navbar = () => {
    return (
        <div className="container">
            <h1>Navbar {useCartContext()}</h1>
        </div>
    );
};

export default Navbar;
