/*Template generated by WebStorm on Wednesday (4/26/23), 9:25 AM.
* Author: kramstyles
* Filename: NavBar.jsx
*/

import {socialLinks, links} from "./data";

const NavBar = () => {
    return (
        <div className="container">
            <nav className="navbar navbar-expand-sm navbar-light bg-secondary">
                <div className="container-fluid">
                    <a className="navbar-brand" href="javascript:void(0)">Custom Navbar</a>
                    <button className="navbar-toggler" type="button" data-bs-toggle="collapse"
                            data-bs-target="#my-custom-navbar-1">
                        <span className="navbar-toggler-icon"></span>
                    </button>
                    <div className="collapse navbar-collapse" id="my-custom-navbar-1">
                        <ul className="navbar-nav me-auto">
                            {links.map((link, index) => {
                                const {text, url} = link;
                                return (<li className="nav-item" key={index}>
                                    <a className="nav-link text-capitalize text-primary" href="javascript:void(0)">{text}</a>
                                </li>)
                            })}
                        </ul>
                        <div className="hide-on-small-devices">
                            {socialLinks.map((link, index) => {
                                const {url, icon} = link;
                                return <a href={url} className="mx-1 fs-4" key={index}>{icon}</a>
                            })}
                        </div>
                    </div>
                </div>
            </nav>
        </div>
    );
};

export default NavBar;
