/*Template generated by WebStorm on Sunday (4/7/24), 12:04 AM.
* Author: kramstyles
* Filename: CartButtons.jsx
*/

const CartButtons = () => {
    return (
        <div className="">
            <h1>CartButtons</h1>
        </div>
    );
};

export default CartButtons;
