/*Template generated by WebStorm on Tuesday (5/9/23), 5:43 PM.
 * Author: kramstyles
 * Filename: Card.jsx
 */

import { useGithubContext } from "../context/context";
import Tab from "./Tab";
const Card = () => {
  const { gitUser } = useGithubContext();
  const {
    login,
    id,
    avatar_url,
    html_url: url,
    name,
    location,
    bio,
    blog,
    company,
    twitter_username,
    created_at,
  } = gitUser;
  return (
    <Tab title="Home">
      <div className="">
        <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro
          synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher
          retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip
          placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
      </div>
    </Tab>
  );
};

export default Card;
