/*Template generated by WebStorm on Tuesday (5/9/23), 5:43 PM.
 * Author: kramstyles
 * Filename: Card.jsx
 */

import { useGithubContext } from "../context/context";
const Card = () => {
  const { gitUser } = useGithubContext();
  const {
    login,
    id,
    avatar_url,
    html_url: url,
    name,
    location,
    bio,
    blog,
    company,
    twitter_username,
    created_at,
  } = gitUser;
  return (
    <div className="container">
      <h1>Card</h1>
    </div>
  );
};

export default Card;
