/*Template generated by WebStorm on Tuesday (5/9/23), 5:45 PM.
* Author: kramstyles
* Filename: Followers.jsx
*/

const Followers = () => {
    return (
        <div className="container">
            <h1>Followers</h1>
        </div>
    );
};

export default Followers;
