/*Template generated by WebStorm on Tuesday (5/9/23), 5:45 PM.
 * Author: kramstyles
 * Filename: Followers.jsx
 */
import Tab from "./Tab";
const Followers = () => {
  return (
    <Tab title="followers">
      <h1>Followers</h1>
    </Tab>
  );
};

export default Followers;
