/*Template generated by WebStorm on Tuesday (5/9/23), 5:46 PM.
 * Author: kramstyles
 * Filename: Info.jsx
 */

const Info = () => {
  return (
    <div className="container">
      <h1>Info</h1>
    </div>
  );
};

export default Info;
