/*Template generated by WebStorm on Tuesday (5/9/23), 5:45 PM.
 * Author: kramstyles
 * Filename: NavBar.jsx
 */

const NavBar = () => {
  return (
    <div className="container">
      <h1>NavBar</h1>
    </div>
  );
};

export default NavBar;
