/*Template generated by WebStorm on Tuesday (5/9/23), 5:43 PM.
 * Author: kramstyles
 * Filename: Repo.jsx
 */

const Repo = () => {
  return (
    <div className="container">
      <h1>Repo</h1>
    </div>
  );
};

export default Repo;
