/*Template generated by WebStorm on Tuesday (5/9/23), 5:45 PM.
 * Author: kramstyles
 * Filename: Search.jsx
 */

import { useState } from "react";
import { ImGithub } from "react-icons/im";

import { InlineForm } from "../../components/Forms";
import {useGithubContext} from "../context/context";

const Search = () => {
  const [user, setUser] = useState("");
  const {requests, getUser, feedback, updateFeedback} = useGithubContext();

  const handleSubmit = (e) => {
      e.preventDefault();
      if (!user) {
          // show negative feedback
          updateFeedback("Name is missing", "is-invalid");
      }else if(requests <= 0) updateFeedback("Login to make more requests", "is-invalid");
      else {
          getUser(user);
          setUser("");
      }
  };

  const handleChange = (e) => {
    setUser(e.target.value);
  };

  const clearAlert = () => {
    updateFeedback();
  };

  return (
    <div className="row my-4">
      <div className="col-md-9">
        <InlineForm
          feedback={feedback.type}
          feedbackMsg={feedback.message}
          handleSubmit={handleSubmit}
          handleChange={handleChange}
          clearAlert={clearAlert}
          icon={<ImGithub />}
          placeholder="kramstyles"
          value={user}
          btnText={`Find ${user}`}
        />
      </div>
        <div className="col-md-3 d-flex align-items-end justify-content-center">
            <h5 className="pb-3 text-primary">Requests ({requests} / 60)</h5>
        </div>
    </div>
  );
};

export default Search;
