/*Template generated by WebStorm on Tuesday (5/9/23), 5:43 PM.
 * Author: kramstyles
 * Filename: User.jsx
 */
import Followers from "./Followers";
import Card from "./Card";
const User = () => {
  return (
    <div className="row my-5">
      <Card />
      <Followers />
    </div>
  );
};

export default User;
