/*Template generated by WebStorm on Tuesday (5/9/23), 5:43 PM.
 * Author: kramstyles
 * Filename: User.jsx
 */

const User = () => {
  return (
    <div className="container">
      <h1>User</h1>
    </div>
  );
};

export default User;
